--------------------------------------------------------
--  Fichier créé - jeudi-mai-06-2021   
--------------------------------------------------------
DROP TABLE "GHAITHM"."ARGENT";
DROP TABLE "GHAITHM"."COURS";
DROP TABLE "GHAITHM"."EXAMEN";
DROP TABLE "GHAITHM"."MEDICAMENT";
DROP TABLE "GHAITHM"."ORDONNACE";
DROP TABLE "GHAITHM"."PROD";
DROP TABLE "GHAITHM"."SUIVI_MEDICAL";
--------------------------------------------------------
--  DDL for Table ARGENT
--------------------------------------------------------

  CREATE TABLE "GHAITHM"."ARGENT" 
   (	"IDAR" NUMBER, 
	"BUDGE" VARCHAR2(20 BYTE), 
	"DATEEF" VARCHAR2(20 BYTE), 
	"NOMPROD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COURS
--------------------------------------------------------

  CREATE TABLE "GHAITHM"."COURS" 
   (	"ID_COURS" NUMBER(*,0), 
	"NOM_MATIERE" VARCHAR2(20 BYTE), 
	"NOM_PROFFESEUR" VARCHAR2(20 BYTE), 
	"PRENOM_PROFFESEUR" VARCHAR2(20 BYTE), 
	"TELEPHONE_PROFFESEUR" NUMBER(*,0), 
	"PRIX" FLOAT(126), 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EXAMEN
--------------------------------------------------------

  CREATE TABLE "GHAITHM"."EXAMEN" 
   (	"ID_EXAMEN" NUMBER, 
	"NOMMATIERE" VARCHAR2(50 BYTE), 
	"COEFFICIENT" FLOAT(126), 
	"SESSION_" VARCHAR2(20 BYTE), 
	"DATE_" VARCHAR2(20 BYTE), 
	"ID_ENFANT" NUMBER, 
	"CLASSE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICAMENT
--------------------------------------------------------

  CREATE TABLE "GHAITHM"."MEDICAMENT" 
   (	"ID_MED" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"PRIX" VARCHAR2(20 BYTE), 
	"COLUMN1" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDONNACE
--------------------------------------------------------

  CREATE TABLE "GHAITHM"."ORDONNACE" 
   (	"ID" NUMBER, 
	"DURÉE" DATE, 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	"PATIENT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROD
--------------------------------------------------------

  CREATE TABLE "GHAITHM"."PROD" 
   (	"IDPROD" NUMBER, 
	"NOMPROD" VARCHAR2(20 BYTE), 
	"DATEEPROD" VARCHAR2(20 BYTE), 
	"PRIX" VARCHAR2(20 BYTE), 
	"CATEGORIE" VARCHAR2(20 BYTE), 
	"COLUMN1" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SUIVI_MEDICAL
--------------------------------------------------------

  CREATE TABLE "GHAITHM"."SUIVI_MEDICAL" 
   (	"ID_S" VARCHAR2(20 BYTE), 
	"POIDS" VARCHAR2(20 BYTE), 
	"TAILLE" VARCHAR2(20 BYTE), 
	"RENDEZ_VOUS" VARCHAR2(20 BYTE), 
	"DESCRPTON" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into GHAITHM.ARGENT
SET DEFINE OFF;
REM INSERTING into GHAITHM.COURS
SET DEFINE OFF;
Insert into GHAITHM.COURS (ID_COURS,NOM_MATIERE,NOM_PROFFESEUR,PRENOM_PROFFESEUR,TELEPHONE_PROFFESEUR,PRIX,TYPE) values ('22222','22','11111','11','1','1','1');
REM INSERTING into GHAITHM.EXAMEN
SET DEFINE OFF;
Insert into GHAITHM.EXAMEN (ID_EXAMEN,NOMMATIERE,COEFFICIENT,SESSION_,DATE_,ID_ENFANT,CLASSE) values ('557',null,'44',null,null,'4','4');
Insert into GHAITHM.EXAMEN (ID_EXAMEN,NOMMATIERE,COEFFICIENT,SESSION_,DATE_,ID_ENFANT,CLASSE) values ('11','11','11','11','11','11','11');
Insert into GHAITHM.EXAMEN (ID_EXAMEN,NOMMATIERE,COEFFICIENT,SESSION_,DATE_,ID_ENFANT,CLASSE) values ('119','info','5','principale','23/04/2021 14:00','0','2A23');
Insert into GHAITHM.EXAMEN (ID_EXAMEN,NOMMATIERE,COEFFICIENT,SESSION_,DATE_,ID_ENFANT,CLASSE) values ('120','info','5','principale','23/04/2021 14:00','1193593','2A23');
Insert into GHAITHM.EXAMEN (ID_EXAMEN,NOMMATIERE,COEFFICIENT,SESSION_,DATE_,ID_ENFANT,CLASSE) values ('222','222','222','222','01/01/2000','22','22');
Insert into GHAITHM.EXAMEN (ID_EXAMEN,NOMMATIERE,COEFFICIENT,SESSION_,DATE_,ID_ENFANT,CLASSE) values ('6666','6666','6666','6666','6666','6666','6666');
REM INSERTING into GHAITHM.MEDICAMENT
SET DEFINE OFF;
REM INSERTING into GHAITHM.ORDONNACE
SET DEFINE OFF;
REM INSERTING into GHAITHM.PROD
SET DEFINE OFF;
REM INSERTING into GHAITHM.SUIVI_MEDICAL
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ARGENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GHAITHM"."ARGENT_PK" ON "GHAITHM"."ARGENT" ("IDAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COURS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GHAITHM"."COURS_PK" ON "GHAITHM"."COURS" ("ID_COURS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ID_EXAMEN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GHAITHM"."ID_EXAMEN_PK" ON "GHAITHM"."EXAMEN" ("ID_EXAMEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEDICAMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GHAITHM"."MEDICAMENT_PK" ON "GHAITHM"."MEDICAMENT" ("ID_MED") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ORDONNACE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GHAITHM"."ORDONNACE_PK" ON "GHAITHM"."ORDONNACE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GHAITHM"."PROD_PK" ON "GHAITHM"."PROD" ("IDPROD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SUIVI_MEDICAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GHAITHM"."SUIVI_MEDICAL_PK" ON "GHAITHM"."SUIVI_MEDICAL" ("ID_S") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ARGENT
--------------------------------------------------------

  ALTER TABLE "GHAITHM"."ARGENT" ADD CONSTRAINT "ARGENT_PK" PRIMARY KEY ("IDAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GHAITHM"."ARGENT" MODIFY ("IDAR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COURS
--------------------------------------------------------

  ALTER TABLE "GHAITHM"."COURS" ADD CONSTRAINT "COURS_PK" PRIMARY KEY ("ID_COURS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GHAITHM"."COURS" MODIFY ("ID_COURS" NOT NULL ENABLE);
  ALTER TABLE "GHAITHM"."COURS" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "GHAITHM"."COURS" MODIFY ("TELEPHONE_PROFFESEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EXAMEN
--------------------------------------------------------

  ALTER TABLE "GHAITHM"."EXAMEN" ADD CONSTRAINT "ID_EXAMEN_PK" PRIMARY KEY ("ID_EXAMEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GHAITHM"."EXAMEN" MODIFY ("ID_ENFANT" NOT NULL ENABLE);
  ALTER TABLE "GHAITHM"."EXAMEN" MODIFY ("COEFFICIENT" NOT NULL ENABLE);
  ALTER TABLE "GHAITHM"."EXAMEN" MODIFY ("ID_EXAMEN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICAMENT
--------------------------------------------------------

  ALTER TABLE "GHAITHM"."MEDICAMENT" ADD CONSTRAINT "MEDICAMENT_PK" PRIMARY KEY ("ID_MED")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GHAITHM"."MEDICAMENT" MODIFY ("ID_MED" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDONNACE
--------------------------------------------------------

  ALTER TABLE "GHAITHM"."ORDONNACE" ADD CONSTRAINT "ORDONNACE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GHAITHM"."ORDONNACE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROD
--------------------------------------------------------

  ALTER TABLE "GHAITHM"."PROD" ADD CONSTRAINT "PROD_PK" PRIMARY KEY ("IDPROD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GHAITHM"."PROD" MODIFY ("IDPROD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUIVI_MEDICAL
--------------------------------------------------------

  ALTER TABLE "GHAITHM"."SUIVI_MEDICAL" ADD CONSTRAINT "SUIVI_MEDICAL_PK" PRIMARY KEY ("ID_S")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GHAITHM"."SUIVI_MEDICAL" MODIFY ("ID_S" NOT NULL ENABLE);
