--------------------------------------------------------
--  Fichier créé - jeudi-avril-01-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COURS
--------------------------------------------------------

  CREATE TABLE "GHAITHM"."COURS" 
   (	"ID_COURS" NUMBER(*,0), 
	"NOM_MATIERE" VARCHAR2(20 BYTE), 
	"NOM_PROFFESEUR" VARCHAR2(20 BYTE), 
	"PRENOM_PROFFESEUR" VARCHAR2(20 BYTE), 
	"TELEPHONE_PROFFESEUR" NUMBER(*,0), 
	"PRIX" FLOAT(126), 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EXAMEN
--------------------------------------------------------

  CREATE TABLE "GHAITHM"."EXAMEN" 
   (	"ID_EXAMEN" NUMBER, 
	"NOMMATIERE" VARCHAR2(50 BYTE), 
	"COEFFICIENT" FLOAT(126), 
	"SESSION_" VARCHAR2(20 BYTE), 
	"DATE_" VARCHAR2(20 BYTE), 
	"ID_ENFANT" NUMBER, 
	"CLASSE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into GHAITHM.COURS
SET DEFINE OFF;
Insert into GHAITHM.COURS (ID_COURS,NOM_MATIERE,NOM_PROFFESEUR,PRENOM_PROFFESEUR,TELEPHONE_PROFFESEUR,PRIX,TYPE) values ('123','info','ghaith','mech','51793002','40','synch');
REM INSERTING into GHAITHM.EXAMEN
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ID_EXAMEN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GHAITHM"."ID_EXAMEN_PK" ON "GHAITHM"."EXAMEN" ("ID_EXAMEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COURS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GHAITHM"."COURS_PK" ON "GHAITHM"."COURS" ("ID_COURS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EXAMEN
--------------------------------------------------------

  ALTER TABLE "GHAITHM"."EXAMEN" ADD CONSTRAINT "ID_EXAMEN_PK" PRIMARY KEY ("ID_EXAMEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GHAITHM"."EXAMEN" MODIFY ("ID_ENFANT" NOT NULL ENABLE);
  ALTER TABLE "GHAITHM"."EXAMEN" MODIFY ("COEFFICIENT" NOT NULL ENABLE);
  ALTER TABLE "GHAITHM"."EXAMEN" MODIFY ("ID_EXAMEN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COURS
--------------------------------------------------------

  ALTER TABLE "GHAITHM"."COURS" ADD CONSTRAINT "COURS_PK" PRIMARY KEY ("ID_COURS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GHAITHM"."COURS" MODIFY ("ID_COURS" NOT NULL ENABLE);
  ALTER TABLE "GHAITHM"."COURS" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "GHAITHM"."COURS" MODIFY ("TELEPHONE_PROFFESEUR" NOT NULL ENABLE);
